cp -r /ql/scripts/wudongdefeng_tem-update/JS_USER_AGENTS.js /ql/scripts
cp -r /ql/scripts/wudongdefeng_tem-update/jdCookie.js /ql/scripts
cp -r /ql/scripts/wudongdefeng_tem-update/jd_feverrun_wind_cjzdgf.js /ql/scripts
cp -r /ql/scripts/wudongdefeng_tem-update/jd_feverrun_wind_wdz.js /ql/scripts
cp -r /ql/scripts/wudongdefeng_tem-update/jd_kingran_wind_drawCenter.js /ql/scripts
cp -r /ql/scripts/wudongdefeng_tem-update/jd_kingran_wind_luck_draw.js /ql/scripts
cp -r /ql/scripts/wudongdefeng_tem-update/jd_kingran_wind_wxCartKoi.js /ql/scripts
cp -r /ql/scripts/wudongdefeng_tem-update/jd_kingran_wind_wxSecond.js /ql/scripts
cp -r /ql/scripts/wudongdefeng_tem-update/jd_kingran_wind_wxUnPackingActivity.js /ql/scripts
cp -r /ql/scripts/wudongdefeng_tem-update/m_jd_fav_shop_gift.js /ql/scripts
cp -r /ql/scripts/wudongdefeng_tem-update/m_jd_wx_addCart.js /ql/scripts
cp -r /ql/scripts/wudongdefeng_tem-update/m_jd_wx_luckDraw.js /ql/scripts
cp -r /ql/scripts/wudongdefeng_tem-update/magic.json /ql/scripts
cp -r /ql/scripts/wudongdefeng_tem-update/ /ql/scripts
cp -r /ql/scripts/wudongdefeng_tem-update/ /ql/scripts
cp -r /ql/scripts/wudongdefeng_tem-update/ /ql/scripts
cp -r /ql/scripts/wudongdefeng_tem-update/ /ql/scripts
cp -r /ql/scripts/wudongdefeng_tem-update/ /ql/scripts
cp -r /ql/scripts/wudongdefeng_tem-update/ /ql/scripts
cp -r /ql/scripts/wudongdefeng_tem-update/ /ql/scripts
cp -r /ql/scripts/wudongdefeng_tem-update/ /ql/scripts
cp -r /ql/scripts/wudongdefeng_tem-update/ /ql/scripts
cp -r /ql/scripts/wudongdefeng_tem-update/ /ql/scripts
cp -r /ql/scripts/wudongdefeng_tem-update/ /ql/scripts
cp -r /ql/scripts/wudongdefeng_tem-update/ /ql/scripts
cp -r /ql/scripts/wudongdefeng_tem-update/ /ql/scripts
cp -r /ql/scripts/wudongdefeng_tem-update/ /ql/scripts
cp -r /ql/scripts/wudongdefeng_tem-update/ /ql/scripts
cp -r /ql/scripts/wudongdefeng_tem-update/ /ql/scripts
cp -r /ql/scripts/wudongdefeng_tem-update/ /ql/scripts
cp -r /ql/scripts/wudongdefeng_tem-update/ /ql/scripts
cp -r /ql/scripts/wudongdefeng_tem-update/ /ql/scripts
cp -r /ql/scripts/wudongdefeng_tem-update/ /ql/scripts
cp -r /ql/scripts/wudongdefeng_tem-update/ /ql/scripts
cp -r /ql/scripts/wudongdefeng_tem-update/ /ql/scripts
cp -r /ql/scripts/wudongdefeng_tem-update/ /ql/scripts
cp -r /ql/scripts/wudongdefeng_tem-update/ /ql/scripts
cp -r /ql/scripts/wudongdefeng_tem-update/ /ql/scripts
cp -r /ql/scripts/wudongdefeng_tem-update/ /ql/scripts
